server:
  port: 8080

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/mavenspringboot?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:dal/mapping/*.xml
  type-aliases-package: com.oldsix.test.datasource.dto

#showSql
logging:
  level:
    com:
      example:
        mapper : debug




